table _Measures
	lineageTag: 7503ad66-c1ad-4d01-b35a-41a894840634

	measure 'Actual Revenue' = ```
			
			CALCULATE(
			[Total Revenue],
			dim_SalesForecastDeals_AFAS[forecast_open_status] = "Gesloten en gescoord"
			)
			
			```
		formatString: 0
		lineageTag: 2cd412a1-3710-4bab-b542-ccad65423082

	measure 'Selected Filter' = ```
			
			VAR MaxFilters = 3
			RETURN
			IF ( 
			    ISFILTERED ( dim_Calendar[Year] ), 
			    VAR __f = FILTERS ( dim_Calendar[Year] ) 
			    VAR __r = COUNTROWS ( __f ) 
			    VAR __t = TOPN ( MaxFilters, __f, dim_Calendar[Year])
			    VAR __d = CONCATENATEX ( __t, dim_Calendar[Year], ", " )
			    VAR __x = "ð—ð—®ð—®ð—¿: " & __d & IF(__r > MaxFilters, " [" & __r-MaxFilters & " Andere filters]") & " " 
			    RETURN __x & UNICHAR(13) & UNICHAR(10)
			) &
			IF ( 
			    ISFILTERED ( dim_Calendar[Quarter] ), 
			    VAR __f = FILTERS ( dim_Calendar[Quarter] ) 
			    VAR __r = COUNTROWS ( __f ) 
			    VAR __t = TOPN ( MaxFilters, __f, dim_Calendar[Quarter])
			    VAR __d = CONCATENATEX ( __t, dim_Calendar[Quarter], ", " )
			    VAR __x = "ð—žð˜„ð—®ð—¿ð˜ð—®ð—®ð—¹: " & __d & IF(__r > MaxFilters, " [" & __r-MaxFilters & " Andere filters]") & " " 
			    RETURN __x & UNICHAR(13) & UNICHAR(10)
			) &
			IF ( 
			    ISFILTERED ( dim_Calendar[MonthName] ), 
			    VAR __f = FILTERS ( dim_Calendar[MonthName] ) 
			    VAR __r = COUNTROWS ( __f ) 
			    VAR __t = TOPN ( MaxFilters, __f, dim_Calendar[MonthName])
			    VAR __d = CONCATENATEX ( __t, dim_Calendar[MonthName], ", " )
			    VAR __x = "ð— ð—®ð—®ð—»ð—±: " & __d & IF(__r > MaxFilters, " [" & __r-MaxFilters & " Andere filters]") & " " 
			    RETURN __x & UNICHAR(13) & UNICHAR(10)
			) &
			IF ( 
			    ISFILTERED ( dim_Organisations_AFAS[naam] ), 
			    VAR __f = FILTERS ( dim_Organisations_AFAS[naam] ) 
			    VAR __r = COUNTROWS ( __f ) 
			    VAR __t = TOPN ( MaxFilters, __f, dim_Organisations_AFAS[naam])
			    VAR __d = CONCATENATEX ( __t, dim_Organisations_AFAS[naam], ", " )
			    VAR __x = "ð—žð—¹ð—®ð—»ð˜: " & __d & IF(__r > MaxFilters, " [" & __r-MaxFilters & " Andere filters]") & " " 
			    RETURN __x & UNICHAR(13) & UNICHAR(10)
			)
			```
		lineageTag: 415d052d-1547-40b3-8d1d-0089e1b9b755

	measure Blank = BLANK()
		formatString: 0
		lineageTag: 978fc16a-0179-4337-9c71-984bbf7ed84e

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

